// Generated by CIRCT firtool-1.62.0
module TensorProcessingEngine(
  input         clock,
                reset,
                io_reset,
                io_control,
  input  [31:0] io_input_0,
                io_input_1,
                io_weight_0,
                io_weight_1,
                io_previousResult,
  output [31:0] io_weightOut_0,
                io_weightOut_1,
                io_inputOut_0,
                io_inputOut_1,
                io_output
);

  reg [31:0] partialSum;
  reg [31:0] outputReg;
  always @(posedge clock) begin
    if (reset) begin
      partialSum <= 32'h0;
      outputReg <= 32'h0;
    end
    else begin
      partialSum <=
        io_input_0 * io_weight_0 + io_input_1 * io_weight_1
        + (io_reset ? 32'h0 : partialSum);
      outputReg <= io_control ? partialSum : io_previousResult;
    end
  end // always @(posedge)
  assign io_weightOut_0 = io_weight_0;
  assign io_weightOut_1 = io_weight_1;
  assign io_inputOut_0 = io_input_0;
  assign io_inputOut_1 = io_input_1;
  assign io_output = outputReg;
endmodule

module BlockPE(
  input         clock,
                reset,
                io_resetVector,
                io_controlVector,
  input  [31:0] io_inputVector_0,
                io_inputVector_1,
                io_inputVector_2,
                io_inputVector_3,
                io_weightVector_0,
                io_weightVector_1,
                io_weightVector_2,
                io_weightVector_3,
                io_previousResultVector_0,
                io_previousResultVector_1,
                io_previousResultVector_2,
                io_previousResultVector_3,
  output [31:0] io_outputVector_0,
                io_outputVector_1,
                io_outputVector_2,
                io_outputVector_3,
                io_inputOutputVector_0,
                io_inputOutputVector_1,
                io_inputOutputVector_2,
                io_inputOutputVector_3,
                io_weightOutputVector_0,
                io_weightOutputVector_1,
                io_weightOutputVector_2,
                io_weightOutputVector_3
);

  wire [31:0] _PEs_3_io_weightOut_0;
  wire [31:0] _PEs_3_io_weightOut_1;
  wire [31:0] _PEs_3_io_inputOut_0;
  wire [31:0] _PEs_3_io_inputOut_1;
  wire [31:0] _PEs_2_io_weightOut_0;
  wire [31:0] _PEs_2_io_weightOut_1;
  wire [31:0] _PEs_2_io_inputOut_0;
  wire [31:0] _PEs_2_io_inputOut_1;
  wire [31:0] _PEs_1_io_weightOut_0;
  wire [31:0] _PEs_1_io_weightOut_1;
  wire [31:0] _PEs_1_io_inputOut_0;
  wire [31:0] _PEs_1_io_inputOut_1;
  wire [31:0] _PEs_0_io_weightOut_0;
  wire [31:0] _PEs_0_io_weightOut_1;
  wire [31:0] _PEs_0_io_inputOut_0;
  wire [31:0] _PEs_0_io_inputOut_1;
  reg  [31:0] weightVectorReg_0;
  reg  [31:0] weightVectorReg_1;
  reg  [31:0] weightVectorReg_2;
  reg  [31:0] weightVectorReg_3;
  reg  [31:0] inputVectorReg_0;
  reg  [31:0] inputVectorReg_1;
  reg  [31:0] inputVectorReg_2;
  reg  [31:0] inputVectorReg_3;
  always @(posedge clock) begin
    if (reset) begin
      weightVectorReg_0 <= 32'h0;
      weightVectorReg_1 <= 32'h0;
      weightVectorReg_2 <= 32'h0;
      weightVectorReg_3 <= 32'h0;
      inputVectorReg_0 <= 32'h0;
      inputVectorReg_1 <= 32'h0;
      inputVectorReg_2 <= 32'h0;
      inputVectorReg_3 <= 32'h0;
    end
    else begin
      weightVectorReg_0 <= _PEs_2_io_weightOut_0;
      weightVectorReg_1 <= _PEs_2_io_weightOut_1;
      weightVectorReg_2 <= _PEs_3_io_weightOut_0;
      weightVectorReg_3 <= _PEs_3_io_weightOut_1;
      inputVectorReg_0 <= _PEs_1_io_inputOut_0;
      inputVectorReg_1 <= _PEs_1_io_inputOut_1;
      inputVectorReg_2 <= _PEs_3_io_inputOut_0;
      inputVectorReg_3 <= _PEs_3_io_inputOut_1;
    end
  end // always @(posedge)
  TensorProcessingEngine PEs_0 (
    .clock             (clock),
    .reset             (reset),
    .io_reset          (io_resetVector),
    .io_control        (io_controlVector),
    .io_input_0        (io_inputVector_0),
    .io_input_1        (io_inputVector_1),
    .io_weight_0       (io_weightVector_0),
    .io_weight_1       (io_weightVector_1),
    .io_previousResult (io_previousResultVector_0),
    .io_weightOut_0    (_PEs_0_io_weightOut_0),
    .io_weightOut_1    (_PEs_0_io_weightOut_1),
    .io_inputOut_0     (_PEs_0_io_inputOut_0),
    .io_inputOut_1     (_PEs_0_io_inputOut_1),
    .io_output         (io_outputVector_0)
  );
  TensorProcessingEngine PEs_1 (
    .clock             (clock),
    .reset             (reset),
    .io_reset          (io_resetVector),
    .io_control        (io_controlVector),
    .io_input_0        (_PEs_0_io_inputOut_0),
    .io_input_1        (_PEs_0_io_inputOut_1),
    .io_weight_0       (io_weightVector_2),
    .io_weight_1       (io_weightVector_3),
    .io_previousResult (io_previousResultVector_1),
    .io_weightOut_0    (_PEs_1_io_weightOut_0),
    .io_weightOut_1    (_PEs_1_io_weightOut_1),
    .io_inputOut_0     (_PEs_1_io_inputOut_0),
    .io_inputOut_1     (_PEs_1_io_inputOut_1),
    .io_output         (io_outputVector_1)
  );
  TensorProcessingEngine PEs_2 (
    .clock             (clock),
    .reset             (reset),
    .io_reset          (io_resetVector),
    .io_control        (io_controlVector),
    .io_input_0        (io_inputVector_2),
    .io_input_1        (io_inputVector_3),
    .io_weight_0       (_PEs_0_io_weightOut_0),
    .io_weight_1       (_PEs_0_io_weightOut_1),
    .io_previousResult (io_previousResultVector_2),
    .io_weightOut_0    (_PEs_2_io_weightOut_0),
    .io_weightOut_1    (_PEs_2_io_weightOut_1),
    .io_inputOut_0     (_PEs_2_io_inputOut_0),
    .io_inputOut_1     (_PEs_2_io_inputOut_1),
    .io_output         (io_outputVector_2)
  );
  TensorProcessingEngine PEs_3 (
    .clock             (clock),
    .reset             (reset),
    .io_reset          (io_resetVector),
    .io_control        (io_controlVector),
    .io_input_0        (_PEs_2_io_inputOut_0),
    .io_input_1        (_PEs_2_io_inputOut_1),
    .io_weight_0       (_PEs_1_io_weightOut_0),
    .io_weight_1       (_PEs_1_io_weightOut_1),
    .io_previousResult (io_previousResultVector_3),
    .io_weightOut_0    (_PEs_3_io_weightOut_0),
    .io_weightOut_1    (_PEs_3_io_weightOut_1),
    .io_inputOut_0     (_PEs_3_io_inputOut_0),
    .io_inputOut_1     (_PEs_3_io_inputOut_1),
    .io_output         (io_outputVector_3)
  );
  assign io_inputOutputVector_0 = inputVectorReg_0;
  assign io_inputOutputVector_1 = inputVectorReg_1;
  assign io_inputOutputVector_2 = inputVectorReg_2;
  assign io_inputOutputVector_3 = inputVectorReg_3;
  assign io_weightOutputVector_0 = weightVectorReg_0;
  assign io_weightOutputVector_1 = weightVectorReg_1;
  assign io_weightOutputVector_2 = weightVectorReg_2;
  assign io_weightOutputVector_3 = weightVectorReg_3;
endmodule

module SystolicTensorArray(
  input         clock,
                reset,
                io_resetVector_0,
                io_resetVector_1,
                io_resetVector_2,
                io_resetVector_3,
                io_controlVector_0,
                io_controlVector_1,
                io_controlVector_2,
                io_controlVector_3,
  input  [31:0] io_inputVector_0,
                io_inputVector_1,
                io_inputVector_2,
                io_inputVector_3,
                io_inputVector_4,
                io_inputVector_5,
                io_inputVector_6,
                io_inputVector_7,
                io_weightVector_0,
                io_weightVector_1,
                io_weightVector_2,
                io_weightVector_3,
                io_weightVector_4,
                io_weightVector_5,
                io_weightVector_6,
                io_weightVector_7,
  output [31:0] io_inputOutVector_0,
                io_inputOutVector_1,
                io_inputOutVector_2,
                io_inputOutVector_3,
                io_inputOutVector_4,
                io_inputOutVector_5,
                io_inputOutVector_6,
                io_inputOutVector_7,
                io_weightOutVector_0,
                io_weightOutVector_1,
                io_weightOutVector_2,
                io_weightOutVector_3,
                io_weightOutVector_4,
                io_weightOutVector_5,
                io_weightOutVector_6,
                io_weightOutVector_7,
                io_outputVector_0,
                io_outputVector_1,
                io_outputVector_2,
                io_outputVector_3,
                io_outputVector_4,
                io_outputVector_5,
                io_outputVector_6,
                io_outputVector_7,
                io_outputVector_8,
                io_outputVector_9,
                io_outputVector_10,
                io_outputVector_11
);

  wire [31:0] _blocks_2_io_outputVector_0;
  wire [31:0] _blocks_2_io_outputVector_1;
  wire [31:0] _blocks_2_io_outputVector_2;
  wire [31:0] _blocks_2_io_outputVector_3;
  wire [31:0] _blocks_2_io_inputOutputVector_0;
  wire [31:0] _blocks_2_io_inputOutputVector_1;
  wire [31:0] _blocks_2_io_inputOutputVector_2;
  wire [31:0] _blocks_2_io_inputOutputVector_3;
  wire [31:0] _blocks_1_io_weightOutputVector_0;
  wire [31:0] _blocks_1_io_weightOutputVector_1;
  wire [31:0] _blocks_1_io_weightOutputVector_2;
  wire [31:0] _blocks_1_io_weightOutputVector_3;
  wire [31:0] _blocks_0_io_inputOutputVector_0;
  wire [31:0] _blocks_0_io_inputOutputVector_1;
  wire [31:0] _blocks_0_io_inputOutputVector_2;
  wire [31:0] _blocks_0_io_inputOutputVector_3;
  wire [31:0] _blocks_0_io_weightOutputVector_0;
  wire [31:0] _blocks_0_io_weightOutputVector_1;
  wire [31:0] _blocks_0_io_weightOutputVector_2;
  wire [31:0] _blocks_0_io_weightOutputVector_3;
  BlockPE blocks_0 (
    .clock                     (clock),
    .reset                     (reset),
    .io_resetVector            (io_resetVector_0),
    .io_controlVector          (io_controlVector_0),
    .io_inputVector_0          (io_inputVector_0),
    .io_inputVector_1          (io_inputVector_1),
    .io_inputVector_2          (io_inputVector_2),
    .io_inputVector_3          (io_inputVector_3),
    .io_weightVector_0         (io_weightVector_0),
    .io_weightVector_1         (io_weightVector_1),
    .io_weightVector_2         (io_weightVector_2),
    .io_weightVector_3         (io_weightVector_3),
    .io_previousResultVector_0 (32'h0),
    .io_previousResultVector_1 (32'h0),
    .io_previousResultVector_2 (32'h0),
    .io_previousResultVector_3 (32'h0),
    .io_outputVector_0         (io_outputVector_0),
    .io_outputVector_1         (io_outputVector_1),
    .io_outputVector_2         (io_outputVector_2),
    .io_outputVector_3         (io_outputVector_3),
    .io_inputOutputVector_0    (_blocks_0_io_inputOutputVector_0),
    .io_inputOutputVector_1    (_blocks_0_io_inputOutputVector_1),
    .io_inputOutputVector_2    (_blocks_0_io_inputOutputVector_2),
    .io_inputOutputVector_3    (_blocks_0_io_inputOutputVector_3),
    .io_weightOutputVector_0   (_blocks_0_io_weightOutputVector_0),
    .io_weightOutputVector_1   (_blocks_0_io_weightOutputVector_1),
    .io_weightOutputVector_2   (_blocks_0_io_weightOutputVector_2),
    .io_weightOutputVector_3   (_blocks_0_io_weightOutputVector_3)
  );
  BlockPE blocks_1 (
    .clock                     (clock),
    .reset                     (reset),
    .io_resetVector            (io_resetVector_1),
    .io_controlVector          (io_controlVector_1),
    .io_inputVector_0          (_blocks_0_io_inputOutputVector_0),
    .io_inputVector_1          (_blocks_0_io_inputOutputVector_1),
    .io_inputVector_2          (_blocks_0_io_inputOutputVector_2),
    .io_inputVector_3          (_blocks_0_io_inputOutputVector_3),
    .io_weightVector_0         (io_weightVector_4),
    .io_weightVector_1         (io_weightVector_5),
    .io_weightVector_2         (io_weightVector_6),
    .io_weightVector_3         (io_weightVector_7),
    .io_previousResultVector_0 (_blocks_2_io_outputVector_0),
    .io_previousResultVector_1 (_blocks_2_io_outputVector_1),
    .io_previousResultVector_2 (_blocks_2_io_outputVector_2),
    .io_previousResultVector_3 (_blocks_2_io_outputVector_3),
    .io_outputVector_0         (io_outputVector_4),
    .io_outputVector_1         (io_outputVector_5),
    .io_outputVector_2         (io_outputVector_6),
    .io_outputVector_3         (io_outputVector_7),
    .io_inputOutputVector_0    (io_inputOutVector_0),
    .io_inputOutputVector_1    (io_inputOutVector_1),
    .io_inputOutputVector_2    (io_inputOutVector_2),
    .io_inputOutputVector_3    (io_inputOutVector_3),
    .io_weightOutputVector_0   (_blocks_1_io_weightOutputVector_0),
    .io_weightOutputVector_1   (_blocks_1_io_weightOutputVector_1),
    .io_weightOutputVector_2   (_blocks_1_io_weightOutputVector_2),
    .io_weightOutputVector_3   (_blocks_1_io_weightOutputVector_3)
  );
  BlockPE blocks_2 (
    .clock                     (clock),
    .reset                     (reset),
    .io_resetVector            (io_resetVector_2),
    .io_controlVector          (io_controlVector_2),
    .io_inputVector_0          (io_inputVector_4),
    .io_inputVector_1          (io_inputVector_5),
    .io_inputVector_2          (io_inputVector_6),
    .io_inputVector_3          (io_inputVector_7),
    .io_weightVector_0         (_blocks_0_io_weightOutputVector_0),
    .io_weightVector_1         (_blocks_0_io_weightOutputVector_1),
    .io_weightVector_2         (_blocks_0_io_weightOutputVector_2),
    .io_weightVector_3         (_blocks_0_io_weightOutputVector_3),
    .io_previousResultVector_0 (32'h0),
    .io_previousResultVector_1 (32'h0),
    .io_previousResultVector_2 (32'h0),
    .io_previousResultVector_3 (32'h0),
    .io_outputVector_0         (_blocks_2_io_outputVector_0),
    .io_outputVector_1         (_blocks_2_io_outputVector_1),
    .io_outputVector_2         (_blocks_2_io_outputVector_2),
    .io_outputVector_3         (_blocks_2_io_outputVector_3),
    .io_inputOutputVector_0    (_blocks_2_io_inputOutputVector_0),
    .io_inputOutputVector_1    (_blocks_2_io_inputOutputVector_1),
    .io_inputOutputVector_2    (_blocks_2_io_inputOutputVector_2),
    .io_inputOutputVector_3    (_blocks_2_io_inputOutputVector_3),
    .io_weightOutputVector_0   (io_weightOutVector_0),
    .io_weightOutputVector_1   (io_weightOutVector_1),
    .io_weightOutputVector_2   (io_weightOutVector_2),
    .io_weightOutputVector_3   (io_weightOutVector_3)
  );
  BlockPE blocks_3 (
    .clock                     (clock),
    .reset                     (reset),
    .io_resetVector            (io_resetVector_3),
    .io_controlVector          (io_controlVector_3),
    .io_inputVector_0          (_blocks_2_io_inputOutputVector_0),
    .io_inputVector_1          (_blocks_2_io_inputOutputVector_1),
    .io_inputVector_2          (_blocks_2_io_inputOutputVector_2),
    .io_inputVector_3          (_blocks_2_io_inputOutputVector_3),
    .io_weightVector_0         (_blocks_1_io_weightOutputVector_0),
    .io_weightVector_1         (_blocks_1_io_weightOutputVector_1),
    .io_weightVector_2         (_blocks_1_io_weightOutputVector_2),
    .io_weightVector_3         (_blocks_1_io_weightOutputVector_3),
    .io_previousResultVector_0 (32'h0),
    .io_previousResultVector_1 (32'h0),
    .io_previousResultVector_2 (32'h0),
    .io_previousResultVector_3 (32'h0),
    .io_outputVector_0         (io_outputVector_8),
    .io_outputVector_1         (io_outputVector_9),
    .io_outputVector_2         (io_outputVector_10),
    .io_outputVector_3         (io_outputVector_11),
    .io_inputOutputVector_0    (io_inputOutVector_4),
    .io_inputOutputVector_1    (io_inputOutVector_5),
    .io_inputOutputVector_2    (io_inputOutVector_6),
    .io_inputOutputVector_3    (io_inputOutVector_7),
    .io_weightOutputVector_0   (io_weightOutVector_4),
    .io_weightOutputVector_1   (io_weightOutVector_5),
    .io_weightOutputVector_2   (io_weightOutVector_6),
    .io_weightOutputVector_3   (io_weightOutVector_7)
  );
endmodule

